name: Test GitHub Secrets

on: [push]

jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verwende Secret
        run: echo "Das Secret ist gesetzt"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
